# Generated by Django 4.2.30 on 2026-05-04 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_alter_costcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='Kỳ kế hoạch')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Ngân sách kế hoạch')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí thực tế')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('status', models.CharField(choices=[('Nhap', 'Nháp'), ('Cho_duyet', 'Chờ duyệt'), ('Da_duyet', 'Đã duyệt')], default='Nhap', max_length=20, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Ghi chú')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt')),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.costcategory', verbose_name='Hạng mục chi phí')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Kế hoạch ngân sách',
                'verbose_name_plural': 'Kế hoạch ngân sách dự án',
                'ordering': ['project', 'period', 'cost_category'],
                'unique_together': {('cost_category', 'project', 'period')},
            },
        ),
    ]
