# Generated by Django 4.2.30 on 2026-05-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_alter_costcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceRecord',
            fields=[
                ('record_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Số biên bản nghiệm thu')),
                ('contract_number', models.CharField(blank=True, max_length=15, verbose_name='Hợp đồng liên quan')),
                ('acceptance_date', models.DateField(verbose_name='Ngày nghiệm thu')),
                ('acceptance_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá trị nghiệm thu (VNĐ)')),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% khối lượng hoàn thành')),
                ('signer_a', models.CharField(max_length=100, verbose_name='Người ký bên A')),
                ('signer_b', models.CharField(max_length=100, verbose_name='Người ký bên B')),
                ('status', models.CharField(choices=[('Nhap', 'Nháp'), ('Da_ky', 'Đã ký'), ('Da_huy', 'Đã hủy')], default='Nhap', max_length=20, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Ghi chú')),
                ('cost_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.costcategory', verbose_name='Hạng mục nghiệm thu')),
            ],
            options={
                'verbose_name': 'Biên bản nghiệm thu',
                'verbose_name_plural': 'Biên bản nghiệm thu',
                'ordering': ['-acceptance_date', 'record_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Số hóa đơn GTGT')),
                ('invoice_type', models.CharField(choices=[('HDB', 'Hóa đơn bán ra'), ('HDM', 'Hóa đơn mua vào')], max_length=5, verbose_name='Loại hóa đơn')),
                ('invoice_date', models.DateField(verbose_name='Ngày lập hóa đơn')),
                ('pre_tax_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tiền chưa thuế')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Thuế suất VAT (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Tiền thuế VAT')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('Chua_TT', 'Chưa thanh toán'), ('TT_1phan', 'Thanh toán 1 phần'), ('Da_TT', 'Đã thanh toán')], default='Chua_TT', max_length=20, verbose_name='Trạng thái')),
                ('acceptance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.acceptancerecord', verbose_name='Biên bản nghiệm thu')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Đối tác')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Hóa đơn GTGT',
                'verbose_name_plural': 'Hóa đơn GTGT',
                'ordering': ['-invoice_date', 'invoice_number'],
            },
        ),
    ]
