# Generated by Django 4.2.30 on 2026-05-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_costcategory_options'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Tên hàng hóa / dịch vụ')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Đơn vị tính')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá chưa VAT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Thuế suất (%)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Thành tiền')),
                ('cost_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.costcategory', verbose_name='Hạng mục chi phí')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='voucher.invoice', verbose_name='Hóa đơn')),
            ],
            options={
                'verbose_name': 'Chi tiết hóa đơn',
                'verbose_name_plural': 'Chi tiết dòng hàng hóa đơn',
            },
        ),
    ]
