# Generated by Django 4.2.30 on 2026-05-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_costcategory_options'),
        ('voucher', '0002_invoicelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Số hợp đồng')),
                ('contract_type', models.CharField(choices=[('HDB', 'Hợp đồng bán ra'), ('HDM', 'Hợp đồng mua vào')], max_length=5, verbose_name='Loại hợp đồng')),
                ('sign_date', models.DateField(verbose_name='Ngày ký')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá trị hợp đồng (VNĐ)')),
                ('payment_terms', models.CharField(blank=True, max_length=500, verbose_name='Điều khoản thanh toán')),
                ('status', models.CharField(choices=[('Hieu_luc', 'Hiệu lực'), ('Thanh_ly', 'Thanh lý'), ('Huy', 'Hủy')], default='Hieu_luc', max_length=20, verbose_name='Trạng thái')),
                ('attachment', models.CharField(blank=True, max_length=300, verbose_name='File đính kèm')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Đối tác')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'ordering': ['-sign_date', 'contract_number'],
            },
        ),
        migrations.RemoveField(
            model_name='acceptancerecord',
            name='contract_number',
        ),
        migrations.AddField(
            model_name='acceptancerecord',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.contract', verbose_name='Hợp đồng liên quan'),
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Thứ tự')),
                ('description', models.CharField(max_length=200, verbose_name='Mô tả đợt')),
                ('completion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% hoàn thành')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền đợt (VNĐ)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn ngày')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Ngày thực tế')),
                ('status', models.CharField(choices=[('Chua_den_han', 'Chưa đến hạn'), ('Den_han', 'Đến hạn'), ('Da_TT', 'Đã thanh toán'), ('Qua_han', 'Quá hạn')], default='Chua_den_han', max_length=20, verbose_name='Trạng thái')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='voucher.contract', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Đợt thanh toán',
                'verbose_name_plural': 'Đợt thanh toán',
                'ordering': ['contract', 'order'],
                'unique_together': {('contract', 'order')},
            },
        ),
    ]
