# Generated by Django 4.2.30 on 2026-05-04 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_costcategory_options'),
        ('voucher', '0003_contract_remove_acceptancerecord_contract_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Số chứng từ')),
                ('voucher_type', models.CharField(choices=[('PT', 'Phiếu thu'), ('PC', 'Phiếu chi')], max_length=3, verbose_name='Loại phiếu')),
                ('voucher_date', models.DateField(verbose_name='Ngày lập chứng từ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền (VNĐ)')),
                ('payment_method', models.CharField(choices=[('Tien_mat', 'Tiền mặt'), ('Chuyen_khoan', 'Chuyển khoản')], max_length=15, verbose_name='Hình thức')),
                ('reason', models.CharField(max_length=300, verbose_name='Lý do')),
                ('status', models.CharField(choices=[('Cho_duyet', 'Chờ duyệt'), ('Da_duyet', 'Đã duyệt'), ('Da_huy', 'Đã hủy')], default='Cho_duyet', max_length=20, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.companybankaccount', verbose_name='Tài khoản ngân hàng')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.contract', verbose_name='Hợp đồng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người lập')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_vouchers', to='main.accountcategory', verbose_name='Tài khoản ghi Có')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_vouchers', to='main.accountcategory', verbose_name='Tài khoản ghi Nợ')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Đối tác')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Phiếu thu/chi',
                'verbose_name_plural': 'Phiếu thu/chi',
                'ordering': ['-voucher_date', 'voucher_number'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Diễn giải')),
                ('cost_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.costcategory', verbose_name='Hạng mục chi phí')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='voucher.voucher', verbose_name='Phiếu thu/chi')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu thu/chi',
                'verbose_name_plural': 'Chi tiết phiếu thu/chi',
            },
        ),
    ]
