# Generated by Django 4.2.30 on 2026-05-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_costcategory_options'),
        ('voucher', '0004_voucher_voucherlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNotice',
            fields=[
                ('notice_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Số chứng từ giấy báo')),
                ('notice_type', models.CharField(choices=[('GBN', 'Giấy báo nợ'), ('GBC', 'Giấy báo có')], max_length=5, verbose_name='Loại giấy báo')),
                ('notice_date', models.DateField(verbose_name='Ngày phát sinh giao dịch NH')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền giao dịch')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Tỷ giá quy đổi')),
                ('to_bank_account', models.CharField(blank=True, max_length=20, verbose_name='Số TKNH chuyển đến')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Nội dung giao dịch')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notices', to='main.accountcategory', verbose_name='Tài khoản ghi Có')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_notices', to='main.accountcategory', verbose_name='Tài khoản ghi Nợ')),
                ('from_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_notices', to='main.companybankaccount', verbose_name='Số TKNH chuyển đi')),
                ('linked_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.voucher', verbose_name='Liên kết phiếu thu/chi')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Đối tác')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Giấy báo nợ/có',
                'verbose_name_plural': 'Giấy báo nợ/có ngân hàng',
                'ordering': ['-notice_date', 'notice_number'],
            },
        ),
    ]
