# Generated by Django 4.2.30 on 2026-05-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_banknotice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='acceptancerecord',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='acceptancerecord',
            name='cost_category',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='cost_category',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='voucherlineitem',
            name='cost_category',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='PaymentSchedule',
        ),
    ]
