# Generated by Django 4.2.30 on 2026-05-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_alter_paymentschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuChi',
            fields=[
            ],
            options={
                'verbose_name': 'Phiếu chi',
                'verbose_name_plural': 'Phiếu chi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voucher.voucher',),
        ),
        migrations.CreateModel(
            name='PhieuThu',
            fields=[
            ],
            options={
                'verbose_name': 'Phiếu thu',
                'verbose_name_plural': 'Phiếu thu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voucher.voucher',),
        ),
        migrations.DeleteModel(
            name='VoucherLineItem',
        ),
    ]
