# Generated by Django 4.2.30 on 2026-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_phieuchi_phieuthu_delete_voucherlineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='status',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người lập'),
        ),
    ]
