# Generated by Django 4.2.30 on 2026-05-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_remove_voucher_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptancerecord',
            options={'verbose_name': 'Biên bản nghiệm thu', 'verbose_name_plural': 'Biên bản nghiệm thu'},
        ),
        migrations.AlterModelOptions(
            name='banknotice',
            options={'verbose_name': 'Giấy báo nợ/có', 'verbose_name_plural': 'Giấy báo nợ/có ngân hàng'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Hóa đơn GTGT', 'verbose_name_plural': 'Hóa đơn GTGT'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'Phiếu thu/chi', 'verbose_name_plural': 'Phiếu thu/chi'},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='payment_method',
        ),
    ]
