# Generated by Django 4.2.30 on 2026-05-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_alter_acceptancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Hóa đơn mua hàng', 'verbose_name_plural': 'Hóa đơn mua hàng'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
    ]
