# Generated by Django 4.2.30 on 2026-05-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_alter_invoice_options_remove_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiayBaoCo',
            fields=[
            ],
            options={
                'verbose_name': 'Giấy báo có',
                'verbose_name_plural': 'Giấy báo có',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voucher.banknotice',),
        ),
        migrations.CreateModel(
            name='GiayBaoNo',
            fields=[
            ],
            options={
                'verbose_name': 'Giấy báo nợ',
                'verbose_name_plural': 'Giấy báo nợ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voucher.banknotice',),
        ),
    ]
