# Generated by Django 4.2.30 on 2026-05-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_giaybaoco_giaybaono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='acceptance',
        ),
        migrations.DeleteModel(
            name='AcceptanceRecord',
        ),
    ]
