# Generated by Django 4.2.30 on 2026-05-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_remove_invoice_acceptance_delete_acceptancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
    ]
