# Generated by Django 4.2.30 on 2026-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0013_remove_invoice_status_remove_invoice_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pre_tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng tiền'),
        ),
    ]
