# Generated by Django 4.2.30 on 2026-05-12 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_accountopeningbalance_unique_together_and_more'),
        ('voucher', '0014_remove_invoice_pre_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Người giao dịch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_invoices', to='main.accountcategory', verbose_name='Tài khoản ghi Có'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_invoices', to='main.accountcategory', verbose_name='Tài khoản ghi Nợ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nội dung'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_10',
            field=models.BooleanField(default=False, verbose_name='Giá trị gia tăng 10%'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Nhà cung cấp'),
        ),
    ]
