# Generated by Django 4.2.30 on 2026-05-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_accountopeningbalance_unique_together_and_more'),
        ('voucher', '0015_invoice_add_supplier_vat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_credit_invoices', to='main.accountcategory', verbose_name='TK Có (VAT 10%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vat_debit_invoices', to='main.accountcategory', verbose_name='TK Nợ (VAT 10%)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_invoices', to='main.accountcategory', verbose_name='TK Có (tổng tiền hàng)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_invoices', to='main.accountcategory', verbose_name='TK Nợ (tổng tiền hàng)'),
        ),
    ]
