# Generated by Django 4.2.30 on 2026-05-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0016_invoice_split_vat_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Phiếu mua hàng', 'verbose_name_plural': 'Phiếu mua hàng'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'verbose_name': 'Mặt hàng', 'verbose_name_plural': 'Mặt hàng'},
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='voucher.invoice', verbose_name='Phiếu mua hàng'),
        ),
    ]
