# Generated by Django 4.2.30 on 2026-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0017_simplify_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lí do'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Đơn vị bán hàng'),
        ),
    ]
