# Generated by Django 4.2.30 on 2026-05-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_alter_accountopeningbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoDuDauKi',
            fields=[
            ],
            options={
                'verbose_name': 'Số dư đầu kì',
                'verbose_name_plural': 'Số dư đầu kì',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.accountopeningbalance',),
        ),
    ]
