# Generated by Django 4.2.30 on 2026-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoCaiTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sổ cái TK',
                'verbose_name_plural': 'Sổ cái TK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoChiTietTK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sổ chi tiết TK',
                'verbose_name_plural': 'Sổ chi tiết TK',
                'managed': False,
            },
        ),
    ]
