# Generated by Django 4.2.30 on 2026-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangKeChiTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Bảng kê chi tiền',
                'verbose_name_plural': 'Bảng kê chi tiền',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaoCaoNoPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Báo cáo nợ phải thu',
                'verbose_name_plural': 'Báo cáo nợ phải thu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaoCaoNoPTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Báo cáo nợ phải trả',
                'verbose_name_plural': 'Báo cáo nợ phải trả',
                'managed': False,
            },
        ),
    ]
