"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import certifi
from pathlib import Path

os.environ['SSL_CERT_FILE'] = certifi.where()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&7q7l)50*+)efg-l#co3!lx-yqh77^@!fzaa)xeb4t^*4g9oz0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'main',
    'voucher',
    'budget',
    'report',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,
        'APP': {
            'client_id': '',     # Add your Google OAuth client ID
            'secret': '',        # Add your Google OAuth secret
        },
    }
}

# ── Email (SMTP) ──────────────────────────────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER     = 'skt.smile1999@gmail.com'
EMAIL_HOST_PASSWORD = 'cpge xdgl vhov uflp'
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

ACCOUNT_PREVENT_ENUMERATION = False
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
LOGIN_REDIRECT_URL = '/admin/'
ACCOUNT_EMAIL_VERIFICATION = 'none'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('vi', _('Vietnamese')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'static_dir']

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_logo": None,
    "site_icon": "images/logo.svg",
    "login_logo": "images/logo.svg",
    "site_brand": "AIBox",
    "welcome_sign": "AIBox - Quản lí chi phí dự án",
    "copyright": "AIBox Company",
    "topmenu_links": [
        {"name": "Dashboard", "url": "/dashboard/", "permissions": ["auth.view_user"]},
    ],
    "custom_css": "css/navbar_tweak.css",
    "hide_apps": ["account", "socialaccount", "sites"],
    "order_with_respect_to": [
        "main",
        "main.project",
        "main.partner",
        "main.bank",
        "main.companybankaccount",
        "main.accountcategory",
        "main.partneropeningbalance",
        "main.accountopeningbalance",
        "budget",
        "budget.projectbudget",
        "voucher",
        "voucher.contract",
        "voucher.paymentschedule",
        "voucher.acceptancerecord",
        "voucher.invoice",
        "voucher.invoicelineitem",
        "voucher.voucher",
        "voucher.voucherlineitem",
        "voucher.banknotice",
        "report",
        "auth",
        "auth.user",
        "auth.group",
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "language_chooser": True,
    "icons": {
        "auth":                        "fas fa-shield-alt",
        "auth.user":                   "fas fa-user-circle",
        "auth.group":                  "fas fa-users",
        "main":                        "fas fa-layer-group",
        "main.accountcategory":        "fas fa-book",
        "main.partner":                "fas fa-handshake",
        "main.bank":                   "fas fa-university",
        "main.companybankaccount":     "fas fa-credit-card",
        "main.project":                "fas fa-project-diagram",
        "main.partneropeningbalance":  "fas fa-balance-scale",
        "main.accountopeningbalance":  "fas fa-coins",
        "voucher":                      "fas fa-file-invoice",
        "voucher.contract":            "fas fa-file-contract",
        "voucher.paymentschedule":     "fas fa-calendar-check",
        "voucher.acceptancerecord":    "fas fa-clipboard-check",
        "voucher.invoice":             "fas fa-file-invoice-dollar",
        "voucher.invoicelineitem":     "fas fa-list-ul",
        "voucher.voucher":             "fas fa-receipt",
        "voucher.voucherlineitem":     "fas fa-list-ul",
        "voucher.banknotice":          "fas fa-university",
        "budget":                      "fas fa-wallet",
        "budget.projectbudget":        "fas fa-chart-pie",
        "report":                      "fas fa-chart-line",
        "report.debtreport":           "fas fa-chart-bar",
    },
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-navy",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-secondary",
        "info": "btn-outline-secondary",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-warning"
    },
    "actions_sticky_top": False
}