# Generated by Django 4.2.30 on 2026-05-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('account_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã TK')),
                ('account_name', models.CharField(max_length=150, verbose_name='Tên tài khoản')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.accountcategory', verbose_name='TK cấp trên')),
            ],
            options={
                'verbose_name': 'Tài khoản kế toán',
                'verbose_name_plural': 'Danh mục tài khoản kế toán',
                'ordering': ['account_code'],
            },
        ),
    ]
