# Generated by Django 4.2.30 on 2026-05-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã đối tác')),
                ('partner_name', models.CharField(max_length=150, verbose_name='Tên đối tác')),
                ('partner_type', models.CharField(choices=[('KH', 'Khách hàng'), ('NCC', 'Nhà cung cấp'), ('NTP', 'Nhà thầu phụ')], max_length=5, verbose_name='Loại đối tác')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Địa chỉ')),
                ('tax_code', models.CharField(blank=True, max_length=15, verbose_name='Mã số thuế')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('representative', models.CharField(blank=True, max_length=100, verbose_name='Người đại diện')),
                ('debt_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Hạn mức công nợ (VNĐ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Danh mục đối tác',
                'ordering': ['partner_code'],
            },
        ),
    ]
