# Generated by Django 4.2.30 on 2026-05-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã ngân hàng')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Tên ngân hàng')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='Chi nhánh')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Ngân hàng',
                'verbose_name_plural': 'Danh mục ngân hàng',
                'ordering': ['bank_code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('account_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(max_length=150, verbose_name='Chủ tài khoản')),
                ('currency', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR')], default='VND', max_length=5, verbose_name='Loại tiền')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư tham chiếu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bank', verbose_name='Ngân hàng')),
            ],
            options={
                'verbose_name': 'Tài khoản ngân hàng',
                'verbose_name_plural': 'Tài khoản ngân hàng công ty',
                'ordering': ['account_number'],
            },
        ),
    ]
