# Generated by Django 4.2.30 on 2026-05-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_bank_companybankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã dự án')),
                ('project_name', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('start_date', models.DateField(verbose_name='Ngày khởi công')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày hoàn thành dự kiến')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Giá trị hợp đồng (VNĐ)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Địa điểm thi công')),
                ('status', models.CharField(choices=[('Dang_thi_cong', 'Đang thi công'), ('Hoan_thanh', 'Hoàn thành'), ('Tam_dung', 'Tạm dừng')], default='Dang_thi_cong', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Ghi chú')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Chủ đầu tư')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Trưởng dự án')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Danh mục dự án',
            },
        ),
    ]
