# Generated by Django 4.2.30 on 2026-05-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'ordering': ['account_code'], 'verbose_name': 'Tài khoản kế toán', 'verbose_name_plural': 'Tài khoản kế toán'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['bank_code'], 'verbose_name': 'Ngân hàng', 'verbose_name_plural': 'Ngân hàng'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['partner_code'], 'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Dự án', 'verbose_name_plural': 'Dự án'},
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('category_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã hạng mục')),
                ('category_name', models.CharField(max_length=150, verbose_name='Tên hạng mục chi phí')),
                ('cost_type', models.CharField(choices=[('Nhan_cong', 'Nhân công'), ('Vat_tu', 'Vật tư'), ('Thiet_bi', 'Thiết bị'), ('Gian_tiep', 'Gián tiếp')], max_length=30, verbose_name='Loại chi phí')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Hạng mục chi phí',
                'verbose_name_plural': 'Hạng mục chi phí dự án',
                'ordering': ['project', 'order', 'category_code'],
            },
        ),
    ]
