# Generated by Django 4.2.30 on 2026-05-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_accountcategory_options_alter_bank_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcategory',
            options={'ordering': ['project', 'order', 'category_code'], 'verbose_name': 'Hạng mục chi phí', 'verbose_name_plural': 'Hạng mục chi phí'},
        ),
    ]
