# Generated by Django 4.2.30 on 2026-05-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_costcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='Kỳ kế toán (VD: 2024-01)')),
                ('debit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư Nợ đầu kỳ')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư Có đầu kỳ')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Ngày nhập số liệu')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accountcategory', verbose_name='Tài khoản (131/331)')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập liệu')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.partner', verbose_name='Đối tác')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='Dự án')),
            ],
            options={
                'verbose_name': 'Số dư nợ công nợ đầu kỳ',
                'verbose_name_plural': 'Số dư nợ công nợ đầu kỳ',
                'ordering': ['period', 'partner', 'account'],
                'unique_together': {('partner', 'account', 'project', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AccountOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10, verbose_name='Kỳ kế toán (VD: 2024-01)')),
                ('debit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư Nợ đầu kỳ')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư Có đầu kỳ')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Ngày nhập số liệu')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accountcategory', verbose_name='Tài khoản kế toán')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập liệu')),
            ],
            options={
                'verbose_name': 'Số dư đầu kỳ tài khoản tổng hợp',
                'verbose_name_plural': 'Số dư đầu kỳ tài khoản tổng hợp',
                'ordering': ['period', 'account'],
                'unique_together': {('account', 'period')},
            },
        ),
    ]
