# Generated by Django 4.2.30 on 2026-05-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_alter_paymentschedule_unique_together_and_more'),
        ('main', '0007_partneropeningbalance_accountopeningbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostCategory',
        ),
    ]
