# Generated by Django 4.2.30 on 2026-05-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_costcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'verbose_name': 'Tài khoản kế toán', 'verbose_name_plural': 'Tài khoản kế toán'},
        ),
        migrations.AlterModelOptions(
            name='accountopeningbalance',
            options={'verbose_name': 'Số dư đầu kỳ tài khoản tổng hợp', 'verbose_name_plural': 'Số dư đầu kỳ tài khoản tổng hợp'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Ngân hàng', 'verbose_name_plural': 'Ngân hàng'},
        ),
        migrations.AlterModelOptions(
            name='companybankaccount',
            options={'verbose_name': 'Tài khoản ngân hàng', 'verbose_name_plural': 'Tài khoản ngân hàng công ty'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.AlterModelOptions(
            name='partneropeningbalance',
            options={'verbose_name': 'Số dư nợ công nợ đầu kỳ', 'verbose_name_plural': 'Số dư nợ công nợ đầu kỳ'},
        ),
    ]
