# Generated by Django 4.2.30 on 2026-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_accountcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('KH', 'Khách hàng'), ('NCC', 'Nhà cung cấp')], max_length=5, verbose_name='Loại đối tác'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Địa chỉ'),
        ),
    ]
