# Generated by Django 4.2.30 on 2026-05-11 16:07

from django.db import migrations, models
import django.db.models.deletion


def remove_duplicate_account_balances(apps, schema_editor):
    AccountOpeningBalance = apps.get_model('main', 'AccountOpeningBalance')
    seen = set()
    for obj in AccountOpeningBalance.objects.order_by('id'):
        if obj.account_id in seen:
            obj.delete()
        else:
            seen.add(obj.account_id)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_project_note_remove_project_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountopeningbalance',
            unique_together=set(),
        ),
        migrations.RunPython(remove_duplicate_account_balances, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.accountcategory', unique=True, verbose_name='Tài khoản kế toán'),
        ),
        migrations.RemoveField(
            model_name='accountopeningbalance',
            name='period',
        ),
    ]
