# Generated by Django 4.2.30 on 2026-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Sao lưu dữ liệu',
                'verbose_name_plural': 'Sao lưu dữ liệu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Khôi phục dữ liệu',
                'verbose_name_plural': 'Khôi phục dữ liệu',
                'managed': False,
            },
        ),
    ]
